### ISSUE TITLE
Colours should be aware of IB presets

### ISSUE THREAD

**Issue by fatuhoku** [jessesquires/JSQFlatButton#5]
I've designed / configured colours in Interface Builder so I want to use those values.
`JSQFlatButton` has no idea of these values and so once I tap the button it sets the background colour to something completely undesirable.

**Comment by jessesquires** [comment]
Hi @fatuhoku - I've decided to discontinue this library. Very sorry!

If you're using iOS 7 or 8, a plain `UIButton` can be configured easily to achieve the same visuals as this library.

**Comment by fatuhoku** [comment]
@jessesquires no worries — sorry that your baby has become obsolete! I've gone for an alternative anyway. Cheers =]
